### ISSUE TITLE
Regression with email_auth, verify_account_grace_period & MFA when password is set on account verification

### ISSUE THREAD

**Issue by janko** [jeremyevans/rodauth#105]
In Rodauth 2.0 the `#allow_email_auth?` method was added and overridden in verify_account_grace_period. The issue is that, this method relies on the account record being loaded, which is currently not always the case.

One such case is when using MFA and delaying setting password until account verification (i.e. setting `verify_account_set_password?` to `true`), with verify_account_grace_period enabled. It's true that verify_account_grace_period feature overrides that setting to `false`, but I wanted to set it to `true` because of UX (in my case, we require 3 additional fields on registration, so I wanted to at least delay asking for password until account verification, to not ask the user too many fields all at once).

In this scenario, if I create the account and call `#authenticated?`, that will call `#two_factor_authentication_setup?`, which will call `#possible_authentication_methods`, which in email_auth will reach the `#allow_email_auth?` branch because password is not set, which will call `#account_in_unverified_grace_period?`, which then tries to access the account record that isn't loaded.

Note that this only happens when the password hash is stored in a separate table (default). When storing the password hash in the `accounts` table, the `#has_password?` method that's called in `#possible_authentication_methods` will load the account record before email_auth's `#possible_authentication_methods` is called.

Here is the minimal self-contained example that reproduces the issue:

```rb
require "roda"
require "sequel"
require "capybara"
require "securerandom"
require "mail"

DB = Sequel.sqlite
DB.extension :date_arithmetic

DB.create_table :accounts do
  primary_key :id
  String :email, null: false, unique: true
  String :status_id, default: 1
end
DB.create_table :account_password_hashes do
  foreign_key :id, :accounts, primary_key: true
  String :password_hash, null: false
end
DB.create_table :account_verification_keys do
  foreign_key :id, :accounts, primary_key: true
  String :key, null: false
  DateTime :requested_at, null: false, default: Sequel::CURRENT_TIMESTAMP
  DateTime :email_last_sent, null: false, default: Sequel::CURRENT_TIMESTAMP
end
DB.create_table :account_email_auth_keys do
  foreign_key :id, :accounts, primary_key: true
  String :key, null: false
  DateTime :deadline, null: false
  DateTime :email_last_sent, null: false, default: Sequel::CURRENT_TIMESTAMP
end
DB.create_table :account_otp_keys do
  foreign_key :id, :accounts, primary_key: true
  String :key, null: false
  Integer :num_failures, null: false, default: 0
  Time :last_use, null: false, default: Sequel.date_sub(Sequel::CURRENT_TIMESTAMP, seconds: 600)
end

Mail.defaults { delivery_method :test }

class App < Roda
  plugin :render, layout: false
  plugin :sessions, secret: SecureRandom.hex(32)

  plugin :rodauth, csrf: :route_csrf do
    enable :email_auth, :verify_account_grace_period, :otp
    set_deadline_values? true
    verify_account_set_password? true
  end

  route do |r|
    r.rodauth
    r.root { "Authenticated? #{rodauth.authenticated?}" }
  end
end

session = Capybara::Session.new(:rack_test, App)
session.visit "/create-account"
session.fill_in "Login", with: "foo@example.com"
session.click_on "Create Account"
```
```
        38: from bug.rb:61:in `<main>'
        37: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.32.2/lib/capybara/session.rb:759:in `block (2 levels) in <class:Session>'
        36: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.32.2/lib/capybara/node/actions.rb:26:in `click_link_or_button'
        35: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.32.2/lib/capybara/node/element.rb:171:in `click'
        34: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.32.2/lib/capybara/node/element.rb:601:in `perform_click_action'
        33: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.32.2/lib/capybara/node/base.rb:83:in `synchronize'
        32: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.32.2/lib/capybara/node/element.rb:601:in `block in perform_click_action'
        31: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.32.2/lib/capybara/node/element.rb:172:in `block in click'
        30: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.32.2/lib/capybara/rack_test/node.rb:137:in `block (2 levels) in <class:Node>'
        29: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.32.2/lib/capybara/rack_test/node.rb:75:in `click'
        28: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.32.2/lib/capybara/rack_test/form.rb:43:in `submit'
        27: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.32.2/lib/capybara/rack_test/browser.rb:35:in `submit'
        26: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.32.2/lib/capybara/rack_test/browser.rb:49:in `process_and_follow_redirects'
        25: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.32.2/lib/capybara/rack_test/browser.rb:49:in `times'
        24: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.32.2/lib/capybara/rack_test/browser.rb:54:in `block in process_and_follow_redirects'
        23: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-3.32.2/lib/capybara/rack_test/browser.rb:70:in `process'
        22: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/2.6.0/forwardable.rb:230:in `get'
        21: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-test-1.1.0/lib/rack/test.rb:58:in `get'
        20: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
        19: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
        18: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
        17: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/roda-3.33.0/lib/roda.rb:53:in `call'
        16: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/roda-3.33.0/lib/roda.rb:360:in `block in base_rack_app_callable'
        15: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/roda-3.33.0/lib/roda/plugins/error_handler.rb:87:in `_roda_handle_main_route'
        14: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/roda-3.33.0/lib/roda.rb:472:in `_roda_handle_main_route'
        13: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/roda-3.33.0/lib/roda.rb:472:in `catch'
        12: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/roda-3.33.0/lib/roda.rb:474:in `block in _roda_handle_main_route'
        11: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/roda-3.33.0/lib/roda.rb:496:in `_roda_run_main_route'
        10: from bug.rb:54:in `block in <class:App>'
         9: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/roda-3.33.0/lib/roda/request.rb:340:in `root'
         8: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/roda-3.33.0/lib/roda/request.rb:501:in `always'
         7: from bug.rb:54:in `block (2 levels) in <class:App>'
         6: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rodauth-2.1.0/lib/rodauth/features/two_factor_base.rb:128:in `authenticated?'
         5: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rodauth-2.1.0/lib/rodauth/features/two_factor_base.rb:187:in `two_factor_authentication_setup?'
         4: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rodauth-2.1.0/lib/rodauth/features/otp.rb:313:in `possible_authentication_methods'
         3: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rodauth-2.1.0/lib/rodauth/features/email_auth.rb:165:in `possible_authentication_methods'
         2: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rodauth-2.1.0/lib/rodauth/features/email_auth.rb:206:in `allow_email_auth?'
         1: from /Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rodauth-2.1.0/lib/rodauth/features/verify_account_grace_period.rb:59:in `allow_email_auth?'
/Users/janko/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rodauth-2.1.0/lib/rodauth/features/verify_account_grace_period.rb:78:in `account_in_unverified_grace_period?': unde
fined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by jeremyevans** [comment]
Thank you for the report and the self contained reproducible example.  This is simple to fix by using the account_id in the session to load the account if it isn't loaded.  I've got it fixed locally, I'll push the changes to GitHub as soon as the tests finish.
