### ISSUE TITLE
reset_password feature renders template in json-only mode

### ISSUE THREAD

**Issue by mwpastore** [jeremyevans/rodauth#11]
The `:reset_password` feature causes a template to be rendered (or attempted to be rendered) upon a failed login attempt in json-only mode. I expect it to return a normal json-encoded login failure, allowing my json:api-consuming front-end to show its own password reset request form (that posts to reset_password_request_route).  Here's a backtrace:

```
HTTP/1.1 500 Internal Server Error
Content-Length: 6565

Puma caught this error: undefined method `h' for #<RodauthApp:0x007fb5b9006308> (NoMethodError)
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/../../../templates/reset-password-request.str:3:in `block in singleton class'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/../../../templates/reset-password-request.str:-3:in `instance_eval'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/../../../templates/reset-password-request.str:-3:in `singleton class'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/../../../templates/reset-password-request.str:-5:in `__tilt_70209204038360'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `call'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `evaluate'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tilt-2.0.5/lib/tilt/template.rb:102:in `render'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda/plugins/render.rb:252:in `render'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/base.rb:485:in `block in _view'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/base.rb:480:in `instance_exec'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/base.rb:480:in `_view'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/jwt.rb:179:in `_view'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/base.rb:236:in `render'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/reset_password.rb:168:in `after_login_failure'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/login.rb:41:in `block (4 levels) in <module:Rodauth>'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/base.rb:317:in `catch'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/base.rb:317:in `catch_error'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/login.rb:29:in `block (3 levels) in <module:Rodauth>'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda.rb:749:in `always'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda.rb:740:in `_verb'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda.rb:522:in `post'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/login.rb:26:in `block (2 levels) in <module:Rodauth>'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth.rb:93:in `instance_exec'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth.rb:93:in `block (2 levels) in route'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda.rb:807:in `if_match'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda.rb:446:in `is'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth.rb:91:in `block in route'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth/features/base.rb:117:in `route!'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rodauth-2406453624de/lib/rodauth.rb:258:in `rodauth'
/Users/mwp/Code/pow/romeo/rodauth_app.rb:84:in `block in <class:RodauthApp>'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda/plugins/middleware.rb:91:in `instance_exec'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda/plugins/middleware.rb:91:in `block in route'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda.rb:243:in `instance_exec'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda.rb:243:in `block in call'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda.rb:241:in `catch'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda.rb:241:in `call'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda.rb:215:in `block in build_rack_app'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda.rb:107:in `call'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda/plugins/middleware.rb:65:in `block in call'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda/plugins/middleware.rb:63:in `catch'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roda-2.18.0/lib/roda/plugins/middleware.rb:63:in `call'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-with_sequel-0.0.1/lib/rack/with_sequel.rb:10:in `block in call'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sequel-4.38.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sequel-4.38.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sequel-4.38.0/lib/sequel/database/connecting.rb:251:in `synchronize'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-with_sequel-0.0.1/lib/rack/with_sequel.rb:9:in `call'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-utf8_sanitizer-1.3.2/lib/rack/utf8_sanitizer.rb:19:in `call'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
/Users/mwp/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by jeremyevans** [comment]
Thanks, I definitely think this is a bug in the reset-password feature, and there may be similar issues in other features.  I'll try to fix it later today.
